# Generated by Django 4.1.6 on 2023-02-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geek_fit', '0004_category_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='training',
        ),
        migrations.RemoveField(
            model_name='training',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='geek_fit.category'),
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
