# Generated by Django 4.1.6 on 2023-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_fit', '0005_remove_category_text_remove_category_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
