# Generated by Django 4.1.6 on 2023-02-12 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_fit', '0006_alter_category_name_alter_training_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='video',
            field=models.FileField(null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
