# Generated by Django 4.1.6 on 2023-02-12 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_fit', '0007_training_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='video',
            field=models.FileField(null=True, upload_to='media/%y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
